function OrderSummary({ toppings, count }) {
  return (
    <div 
      className="
        order-summary 
        w-full                 
        max-w-[420px]        
        min-h-[202px]       
        flex                  
        flex-col               
        mt-[40px] 
        pl-[49px] 
        pt-[42px]  
        rounded-[6px]     
        border-[1px]       
        border-[#D9D9D9]   
        lg:w-full
        lg:min-w-[350px]   
        lg:max-h-[197px]
        lg:ml-auto
        lg:col-start-2
        lg:row-start-1
        lg:bg-[#FAF7F2]
      "
    >
      <h3 
        className="
          font-['Barlow']      
          font-[600]       
          text-[20px]    
          lg:w-full
          lg:max-w-[154px]   
          lg:max-h-[25px]
        "
      >
        Sipariş Toplamı
      </h3>

      <div 
        className="
          choices-price 
          w-full              
          max-w-[302px]      
          min-h-[25px]      
          flex                 
          flex-row             
          gap-[75px]        
          mt-[22px]      
          lg:w-full
          lg:max-w-[253px]   
          lg:gap-[26px]
        "
      >
        <span 
          className="
            choices 
            w-full 
            max-w-[154px]              
            min-h-[25px]     
            font-['Barlow']      
            font-[600]       
            text-[18px]       
            text-[#5F5F5F]       
          "
        >
          Seçimler
        </span>
        <span 
          className="
            choices-summary 
            w-full               
            max-w-[73px]      
            min-h-[25px]     
            font-['Barlow']    
            font-[600]       
            text-[18px]       
            text-[#5F5F5F]     
          "
        >
          {toppings.length * 5}.00₺
        </span>
      </div>

      <div 
        className="
          total-price 
          w-full              
          max-w-[302px]     
          min-h-[25px]      
          flex                
          flex-row             
          gap-[75px]        
          mt-[12px]  
          lg:gap-[26px]       
        "
      >
        <p 
          className="
            total 
            w-full 
            max-w-[154px]             
            min-h-[25px]      
            font-['Barlow']      
            font-[600]       
            text-[18px]       
            text-[#CE2829]       
          "
        >
          Toplam
        </p>
        <p 
          className="
            price-total 
            w-full              
            max-w-[73px]      
            min-h-[25px]     
            font-['Barlow']      
            font-[600]       
            text-[18px]      
            text-[#CE2829]       
          "
        >
          {(85.5 + toppings.length * 5) * count}₺
        </p>
      </div>
    </div>
  );
}

export default OrderSummary;