function ProductInfo({ children }) {
  return (
    <div 
      className="
        item-info              
        w-full                 
        max-w-[420px]        
        h-full        
        flex                   
        flex-col               
        justify-between  
        lg:w-full   
        lg:min-w-[532px]  
      "
    >
      <p 
        className="
          item-name           
          w-full               
          max-w-[420px]      
          min-h-[56px]      
          font-['Barlow']      
          font-[600]       
          text-[27px] 
          lg:w-full
          lg:min-w-[488px]   
          lg:text-[22px]   
        "
      >
        Position Absolute Acı Pizza
      </p>

      <div 
        className="
          item-info-row        
          w-full               
          max-w-[420px]      
          min-h-[37px]      
          flex                 
          justify-between    
          mt-[16px] 
          gap-[174px] 
          lg:w-full
          lg:min-w-[531px] 
        "
      >
        <span 
          className="
            price              
            w-full             
            max-w-[106px]    
            min-h-[37px]    
            font-['Barlow']    
            font-[700]     
            text-[28px]  
            lg:w-full
            lg:min-w-[106px]   
          "
        >
          85.50₺
        </span>
        <div 
          className="
            votes              
            w-full             
            max-w-[140px]    
            min-h-[27px]    
            flex
            justify-between  
            lg:w-full
            lg:max-w-[118px]                  
          "
        >
          <span 
            className="
              rating           
              w-full           
              max-w-[30px]  
              min-h-[27px]  
              font-['Barlow']  
              font-[400]   
              text-[20px]   
              lg:w-full
              lg:max-w-[25px] 
              lg:text-[16px]
            "
          >
            4.9
          </span>
          <span 
            className="
              comment-count    
              w-full           
              max-w-[46px]  
              min-h-[27px]  
              font-['Barlow']  
              font-[400]   
              text-[20px]   
              lg:w-full
              lg:max-w-[38.5px] 
              lg:text-[16px]
            "
          >
            (200)
          </span>
        </div>
      </div>

      <div 
        className="
          item-details         
          w-full               
          max-w-[420px]      
          h-auto  
          flex
          justify-center
          flex-col  
          mt-[21px] 
          lg:w-full
          lg:min-w-[532px]  
        "
      >
        <p 
          className="
            description        
            w-full             
            max-w-[409px]    
            h-auto    
            font-['Barlow']    
            font-[400]     
            text-[20px]     
            leading-[29px]  
            mt-[21px] 
            lg:w-full
            lg:min-w-[532px]    
            lg:text-[16px] 
            lg:max-h-[173px]  
          "
        >
          Frontent Dev olarak hala position:absolute kullanıyorsan bu çok acı pizza tam sana göre. Pizza, domates, peynir ve genellikle çeşitli diğer malzemelerle kaplanmış, daha sonra geleneksel olarak odun ateşinde bir fırında yüksek sıcaklıkta pişirilen, genellikle yuvarlak, düzleştirilmiş mayalı buğday bazlı hamurdan oluşan İtalyan kökenli lezzetli bir yemektir. . Küçük bir pizzaya bazen pizzetta denir.
        </p>

        {children}
      </div>
    </div>
  );
}

export default ProductInfo;